ifndef SUBDIR_MK
SUBDIR_MK=true

INCLUDE_MAKEFILES?=.

ifdef SUBDIR
.PHONY: ${SUBDIR}
${SUBDIR}::
	${MAKE} -C $@ -I ${INCLUDE_MAKEFILES} ${MAKECMDGOALS}
endif

SUBDIR_ALL_GOALS?=yes

ifeq (${SUBDIR_ALL_GOALS},yes)
ifneq (${MAKECMDGOALS},)
.PHONY: ${MAKECMDGOALS}
${MAKECMDGOALS}: ${SUBDIR}
else
${.DEFAULT_GOAL}: ${SUBDIR}
endif
endif

endif
